<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="Current">

	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<PackageVersion Include="DevilDaggersInfo.Core" Version="0.16.0"/>
		<PackageVersion Include="DevilDaggersInfo.Web.ApiSpec.Tools" Version="2.0.0"/>
		<PackageVersion Include="Hexa.NET.ImGui" Version="2.2.9"/>
		<PackageVersion Include="NoahStolk.EnumGenerator" Version="0.6.0"/>
		<PackageVersion Include="NativeFileDialogSharp" Version="0.5.0"/>
		<PackageVersion Include="Serilog.Sinks.File" Version="7.0.0"/>
		<PackageVersion Include="Silk.NET.GLFW" Version="2.23.0"/>
		<PackageVersion Include="Silk.NET.OpenGL" Version="2.23.0"/>
		<PackageVersion Include="StrongInject" Version="1.4.4"/>
	</ItemGroup>

	<ItemGroup Label="Static code analysis">
		<GlobalPackageReference Include="Nullable.Extended.Analyzer" Version="1.15.6581"/>
		<GlobalPackageReference Include="Roslynator.Analyzers" Version="5.0.0"/>
		<GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.33.0.1635"/>
		<GlobalPackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556"/>
	</ItemGroup>

</Project>
