on:
    push:
        branches:
            - main
            # TODO: Remove.
            - set-up-ci-release
jobs:
    release:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            -   name: Set up dotnet
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '8.0.100'
                    include-prerelease: false
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Build and test
                run: dotnet test src/DevilDaggersInfo.Tools.sln -c Release
            # TODO: Add encryption.ini via secrets.
            -   name: Build optimized release
                run: >
                    dotnet publish src/DevilDaggersInfo.Tools/DevilDaggersInfo.Tools.csproj
                    -p:PublishTrimmed=True
                    -p:EnableCompressionInSingleFile=True
                    -p:PublishReadyToRun=False
                    -p:PublishProtocol=FileSystem
                    -p:TargetFramework=net8.0
                    -p:RuntimeIdentifier=win-x64
                    -p:Platform=x64
                    -p:Configuration=Release
                    -p:PublishDir=release-win-x64
                    -p:PublishSingleFile=True
                    -p:SelfContained=True
                    -p:PublishMethod=SELF_CONTAINED
                    -p:OutputType=WinExe
            -   name: Install zip
                uses: montudor/action-zip@v1
            -   name: Zip output
                run: zip -qq -r ddinfo-tools-win-x64.zip release-win-x64
                working-directory: src/DevilDaggersInfo.Tools
            -   name: Release
                uses: softprops/action-gh-release@v1
                if: ${{ startsWith(github.commit, 'Release') }}
                with:
                    files: ddinfo-tools-win-x64.zip
                    generate_release_notes: true
#            -   name: Create release
#                id: create_release
#                uses: ChanTsune/release-with-commit@v2.8.0
#                with:
#                    regexp: "Release ((\\d+([.]\\d+)*)-(alpha|beta|rc)\\d*)((\\s|\\S)*)"
#                    regexp_options: "us"
#                    release_name: "Version $1"
#                    tag_name: "v$1"
#                    body: "$5"
#                    draft: true
#                    prerelease: true
#                env:
#                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

#                uses: marvinpinto/action-automatic-releases@latest
#                with:
#                    repo_token: ${{ secrets.GITHUB_TOKEN }}
#                    prerelease: true
#                    files: src/DevilDaggersInfo.Tools/ddinfo-tools-win-x64.zip
